# IMPORT NUMPY

In [14]:
import numpy as np

# PROPERTIES OF ARRAY

In [12]:
a1 = np.array([10,20,30,40])

In [5]:
a1

array([10, 20, 30, 40])

In [6]:
a1.ndim

1

In [7]:
a1.dtype

dtype('int32')

In [8]:
a1.shape

(4,)

In [9]:
a1.shape

(4,)

In [10]:
a1.size

4

In [11]:
a1.itemsize

4

# RESHAPING ARRAY

In [15]:
a = np.array(range(10))

In [16]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a = a.reshape((2,5))

In [20]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
a.shape

(2, 5)

# TRANSPOSE

In [23]:
b = np.array([[2,3,4],[6,5,8]])

In [24]:
b

array([[2, 3, 4],
       [6, 5, 8]])

In [25]:
b.transpose()

array([[2, 6],
       [3, 5],
       [4, 8]])

# INDEXING AND SLICING

In [26]:
C = np.array([10,20,30,40,50,60,70,80])

In [27]:
C

array([10, 20, 30, 40, 50, 60, 70, 80])

In [28]:
C[0]

10

In [32]:
C[-3]

60

In [30]:
C[2:]

array([30, 40, 50, 60, 70, 80])

In [31]:
C[2:5]

array([30, 40, 50])

In [33]:
C1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [34]:
C1[0:,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [35]:
C1[-1:,-2:]

array([[ 9, 10]])